// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package cluster

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.KMSEncryptionKey, b.ko.Spec.KMSEncryptionKey) {
		delta.Add("Spec.KMSEncryptionKey", a.ko.Spec.KMSEncryptionKey, b.ko.Spec.KMSEncryptionKey)
	} else if a.ko.Spec.KMSEncryptionKey != nil && b.ko.Spec.KMSEncryptionKey != nil {
		if *a.ko.Spec.KMSEncryptionKey != *b.ko.Spec.KMSEncryptionKey {
			delta.Add("Spec.KMSEncryptionKey", a.ko.Spec.KMSEncryptionKey, b.ko.Spec.KMSEncryptionKey)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.KMSEncryptionKeyRef, b.ko.Spec.KMSEncryptionKeyRef) {
		delta.Add("Spec.KMSEncryptionKeyRef", a.ko.Spec.KMSEncryptionKeyRef, b.ko.Spec.KMSEncryptionKeyRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MultiRegionProperties, b.ko.Spec.MultiRegionProperties) {
		delta.Add("Spec.MultiRegionProperties", a.ko.Spec.MultiRegionProperties, b.ko.Spec.MultiRegionProperties)
	} else if a.ko.Spec.MultiRegionProperties != nil && b.ko.Spec.MultiRegionProperties != nil {
		if len(a.ko.Spec.MultiRegionProperties.Clusters) != len(b.ko.Spec.MultiRegionProperties.Clusters) {
			delta.Add("Spec.MultiRegionProperties.Clusters", a.ko.Spec.MultiRegionProperties.Clusters, b.ko.Spec.MultiRegionProperties.Clusters)
		} else if len(a.ko.Spec.MultiRegionProperties.Clusters) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.MultiRegionProperties.Clusters, b.ko.Spec.MultiRegionProperties.Clusters) {
				delta.Add("Spec.MultiRegionProperties.Clusters", a.ko.Spec.MultiRegionProperties.Clusters, b.ko.Spec.MultiRegionProperties.Clusters)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.MultiRegionProperties.WitnessRegion, b.ko.Spec.MultiRegionProperties.WitnessRegion) {
			delta.Add("Spec.MultiRegionProperties.WitnessRegion", a.ko.Spec.MultiRegionProperties.WitnessRegion, b.ko.Spec.MultiRegionProperties.WitnessRegion)
		} else if a.ko.Spec.MultiRegionProperties.WitnessRegion != nil && b.ko.Spec.MultiRegionProperties.WitnessRegion != nil {
			if *a.ko.Spec.MultiRegionProperties.WitnessRegion != *b.ko.Spec.MultiRegionProperties.WitnessRegion {
				delta.Add("Spec.MultiRegionProperties.WitnessRegion", a.ko.Spec.MultiRegionProperties.WitnessRegion, b.ko.Spec.MultiRegionProperties.WitnessRegion)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Policy, b.ko.Spec.Policy) {
		delta.Add("Spec.Policy", a.ko.Spec.Policy, b.ko.Spec.Policy)
	} else if a.ko.Spec.Policy != nil && b.ko.Spec.Policy != nil {
		if equal, err := ackcompare.IAMPolicyDocumentEqual(*a.ko.Spec.Policy, *b.ko.Spec.Policy); err != nil || !equal {
			delta.Add("Spec.Policy", a.ko.Spec.Policy, b.ko.Spec.Policy)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
